using System;
using System.Collections.Generic;

public struct GridPos : IEquatable<GridPos>
{
    public int x, y;

    public GridPos(int x, int y)
    {
        this.x = x;
        this.y = y;
    }

    public int GetIndex(int width)
    {
        return y * width + x;
    }
    
    public GridPos Clamp(int width, int height)
    {
        GridPos p = this;
        if (x < 0)
            p.x = 0;
        else if (x >= width)
            p.x = width - 1;
        if (y < 0)
            p.y = 0;
        else if (y >= height)
            p.y = height - 1;
        return p;
    }

    public static bool operator ==(GridPos a, GridPos b)
    {
        return a.x == b.x && a.y == b.y;
    }
    public static bool operator !=(GridPos a, GridPos b)
    {
        return a.x != b.x || a.y != b.y;
    }

    #region AutoGenerated
    public override bool Equals(object obj)
    {
        return obj is GridPos && Equals((GridPos)obj);
    }

    bool IEquatable<GridPos>.Equals(GridPos other)
    {
        return this == other;
    }

    public override int GetHashCode()
    {
        var hashCode = 1502939027;
        hashCode = hashCode * -1521134295 + x.GetHashCode();
        hashCode = hashCode * -1521134295 + y.GetHashCode();
        return hashCode;
    }

    #endregion

}
